import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)
CPPPATH = []

src = ['App.cpp']
src += Glob('Common/DataProc/*.cpp')
src += Glob('Pages/*.cpp')
src += Glob('Pages/_Template/*.cpp')
src += Glob('Pages/Dialplate/*.cpp')
src += Glob('Pages/LiveMap/*.cpp')
src += Glob('Pages/StartUp/*.cpp')
src += Glob('Pages/StatusBar/*.cpp')
src += Glob('Pages/SystemInfos/*.cpp')
src += Glob('Resource/*.cpp')
src += Glob('Resource/Font/*.c')
src += Glob('Resource/Image/*.c')
src += Glob('Utils/DataCenter/*.cpp')
src += Glob('Utils/DataCenter/PingPongBuffer/*.c')
src += Glob('Utils/GPX/*.cpp')
src += Glob('Utils/GPX_Parser/*.cpp')
src += Glob('Utils/lv_anim_label/*.c')
src += Glob('Utils/lv_ext/*.c')
src += Glob('Utils/lv_ext/*.cpp')
src += Glob('Utils/lv_poly_line/*.cpp')
src += Glob('Utils/MapConv/*.cpp')
src += Glob('Utils/MapConv/GPS_Transform/*.c')
src += Glob('Utils/MapConv/TileSystem/*.cpp')
src += Glob('Utils/PageManager/*.cpp')
src += Glob('Utils/PointContainer/*.cpp')
src += Glob('Utils/ResourceManager/*.cpp')
src += Glob('Utils/StorageService/*.cpp')
src += Glob('Utils/TileConv/*.cpp')
src += Glob('Utils/Time/*.cpp')
src += Glob('Utils/TonePlayer/*.cpp')
src += Glob('Utils/TrackFilter/*.cpp')

path = [
    cwd,
    # cwd + '/Common/DataProc',
    # cwd + '/Common/HAL',
    # cwd + '/Common/Music',
    # cwd + '/Config',
    # cwd + '/Pages',
    # cwd + '/Pages/_Template',
    # cwd + '/Pages/Dialplate',
    # cwd + '/Pages/LiveMap',
    # cwd + '/Pages/StartUp',
    # cwd + '/Pages/StatusBar',
    # cwd + '/Pages/SystemInfos',
    # cwd + '/Resource',
    cwd + '/Utils/ArduinoJson/src',
    # cwd + '/Utils/DataCenter',
    # cwd + '/Utils/DataCenter/PingPongBuffer',
    # cwd + '/Utils/GPX',
    # cwd + '/Utils/GPX_Parser',
    # cwd + '/Utils/Filters',
    # cwd + '/Utils/lv_anim_label',
    # cwd + '/Utils/lv_ext',
    # cwd + '/Utils/lv_poly_line',
    # cwd + '/Utils/MapConv',
    # cwd + '/Utils/MapConv/GPS_Transform',
    # cwd + '/Utils/MapConv/TileSystem',
    # cwd + '/Utils/PageManager',
    # cwd + '/Utils/PointContainer',
    # cwd + '/Utils/ResourceManager',
    # cwd + '/Utils/StorageService',
    # cwd + '/Utils/TileConv',
    # cwd + '/Utils/Time',
    # cwd + '/Utils/TonePlayer',
    # cwd + '/Utils/TrackFilter',
]

objs = DefineGroup('', src, depend = [''], CPPPATH = path)

exclude_dirs = ['lvgl']

for item in list:
    if item not in exclude_dirs:
        if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
            objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
